"use client";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import { RefsProvider } from "@/context/RefsContext";

// export const metadata = {
//   title: "Land of Cult",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <RefsProvider>
          <Header />
          <main>{children}</main> 
          <Footer />
        </RefsProvider>
      </body>
    </html>
  );
}
